### ISSUE TITLE
Getting the exception on starting server (did nothing, just cloned and ran)

### ISSUE THREAD

**Issue by abhaytalreja** [VulcanJS/Screenings#7]
Hi Sacha,

First of all, awesome work, i was looking to create something similar for myself. But, seems like you've done all the hard work... I wanted to try it out.. i came across this exception while running "meteor".

All i did was cloned the repo. I also took the updated from 13hrs ago from you. Is it a working copy?

Is it something to do with Windows machine? I am using windows.

```
C:\Users\xyz\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windo
ws.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
Error: Unable to allocate ArrayBuffer.
    at C_MINISAT (packages/logic-solver/minisat.js:3:1)
    at new MiniSat (packages/logic-solver/minisat_wrapper.js:19:1)
    at new Logic.Solver (packages/logic-solver/logic.js:274:1)
    at packages/constraint-solver/solver.js:533:1
    at Function.time (C:\Users\xyz\AppData\Local\.meteor\packages\meteor-
```

**Comment by SachaG** [comment]
It does seem like it might be a Windows error. In any case I haven't run into it myself before, sorry…

**Comment by abhaytalreja** [comment]
You are right, it was not windows error. I had not installed prerender. Although, after i installed prerender i am getting the below exception. Any thoughts on this one?

```
   While building the application:

   node_modules/prerender-node/node_modules/request/node_modules/form-data/node_
modules/combined-stream/node_modules/delayed-stream/test/run.js:1:15:
   Unexpected token ILLEGAL

   node_modules/prerender-node/node_modules/request/node_modules/form-data/node_
modules/async/support/sync-package-managers.js:1:15:
   Unexpected token ILLEGAL

   node_modules\prerender-node\node_modules\request\node_modules\node-uuid\test\
test.html:1:
   bad formatting in HTML template

=> Your application has errors. Waiting for file change.
```

**Comment by abhaytalreja** [comment]
Okay, so after doing some research, figured out. The problem was i was using prerender but had not created my settings file. I quickly created my settings file and ran the meteor app.

It worked. Thank you! Closing this issue...

**Comment by SachaG** [comment]
Oh ok, I guess Windows errors are a bit different from what I'm used to, sorry I didn't recognize the issue sooner! By the way, I forgot to mention but I recommend you use the Zeiss theme instead of this repo: https://github.com/TelescopeJS/Zeiss

It's pretty much the same thing, just without any Screenings-specific code like the Prerender stuff.
