### ISSUE TITLE
Screenings Theme breaking after the latest update

### ISSUE THREAD

**Issue by abhaytalreja** [VulcanJS/Screenings#8]
Hi Sacha,

I've been playing around with the screenings theme, however after i took the update for telescope (using meteor update) the left nav is breaking, all the links are breaking.

Also, i think you moved the code for screenings and made it to just the theme? - Can you please point me to that repo, so i can keep the workspace in sync. i hope it's still public :+1: 

Once again, thank you! i am learning and will love to contribute to the overall telescope project.

![image](https://cloud.githubusercontent.com/assets/1915902/9297777/8f1d0466-4472-11e5-8042-bc67cb0c945a.png)

**Comment by SachaG** [comment]
Sure, here's the theme: https://github.com/TelescopeJS/Zeiss

Maybe try using that, and then make sure you're running Telescope's `devel` branch?

**Comment by abhaytalreja** [comment]
Got you! thanks... and for anyone who is looking to know more about the theme, there is a video series.

Closing the issue.

https://www.youtube.com/playlist?list=PLBoa_Q6hVeSzw6cGRaKInzNc3saxWcH4M
